In [1]:
import numpy as np
a = [10,2030,40]
type(a)

list

In [2]:
x = np.array(a)
print(x)

[  10 2030   40]


In [3]:
type(x)

numpy.ndarray

In [4]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])

In [5]:
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [8]:
a = [1,2,3,4]
b = [10,20,30]
x = np.array([a,b])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [9]:
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [10]:
x = np.array([1,2,3,4], dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [11]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [15]:
x = np.random.rand(2,5)
print(x)

[[0.627087   0.32208508 0.32191088 0.92518532 0.84102759]
 [0.90210097 0.35223096 0.40804802 0.83702475 0.31488109]]


In [17]:
np.random.randint(1,20, size = (3,3))

array([[ 5,  4, 14],
       [17,  3,  4],
       [19, 15, 15]], dtype=int32)

In [18]:
np.random.rand(2,5)

array([[0.0813549 , 0.71100379, 0.71577693, 0.84208624, 0.59937157],
       [0.2713751 , 0.7289154 , 0.51868622, 0.0646128 , 0.41517014]])

In [20]:
np.random.choice([2,3,4,7,8,10])

np.int64(8)

In [21]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [22]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [23]:
x = np.eye(4, k = -1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [24]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [25]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
a = [10,20,30,40,50]
x = np.array(a)
print(x)

[10 20 30 40 50]


In [29]:
x.ndim

1

In [30]:
b = [1,2,3,4,5]
y = np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [31]:
y.ndim

2

In [32]:
y.shape

(2, 5)

In [33]:
y.size 

10

In [34]:
a = np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [35]:
np.reshape(a, (2,2))

array([[ 3,  6],
       [ 9, 12]])

In [36]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [37]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
x.size

15

In [39]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [40]:
x = np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [41]:
y = x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [42]:
z = np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [44]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [45]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [46]:
a[2:6]

array([3, 4, 5, 6])

In [47]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
x[1,2]

np.int64(6)

In [49]:
x[1][2]

np.int64(6)

In [50]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [51]:
a = np.arange(1,6)
b = np.arange(6,11)

In [52]:
print(a)

[1 2 3 4 5]


In [53]:
print(b)

[ 6  7  8  9 10]


In [54]:
x = np.vstack((a,b))

In [55]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [56]:
x = np.hstack((a,b))

In [57]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [60]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
b = np.arange(10,19).reshape(3,3)
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [62]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [63]:
np.concatenate((a,b),axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [64]:
a = np.arange(10,21,2)
print(a)

[10 12 14 16 18 20]


In [65]:
b = np.array([[2],[2]])
print(b)

[[2]
 [2]]


In [66]:
z = a+b
print(z)

[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [67]:
a = np.arange(10,21,2)
a+2

array([12, 14, 16, 18, 20, 22])

In [68]:
a - b

array([[ 8, 10, 12, 14, 16, 18],
       [ 8, 10, 12, 14, 16, 18]])

In [69]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [70]:
a = np.ones((3,3))
b = np.array([2])
print(a)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [71]:
print(b)

[2]


In [72]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [73]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [74]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [75]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [76]:
a - 1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [77]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [78]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [79]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [80]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [81]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
a = np.arange(5,15,2)
print(a)

[ 5  7  9 11 13]


In [83]:
np.mean(a)

np.float64(9.0)

In [84]:
np.median(a)

np.float64(9.0)

In [85]:
np.std(a)

np.float64(2.8284271247461903)

In [86]:
a = np.array([[1,6],[4,3]])
print(a)

[[1 6]
 [4 3]]


In [87]:
print(np.min(a, axis = 0))

[1 3]


In [88]:
print(np.min(a, axis = 1))

[1 3]


In [89]:
print(np.max(a, axis = 0))


[4 6]


In [90]:
print(np.max(a, axis = 1))

[6 4]


In [91]:
a = np.array([1,4,3,10,20])
x = np.sort(a, kind = 'mergesort')
print(x)

[ 1  3  4 10 20]


In [94]:
A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [95]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [96]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [97]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])