In [13]:
import numpy as np
a = [10,20,30,40]
type(a)


list

In [2]:
x = np.array(a)
print(x)


[10 20 30 40]


In [3]:
type(x)

numpy.ndarray

In [4]:
a = [1,2,3,4] 
b = [10,20,30,40]
x = np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [12]:
a = [1,2,3,4]
b = [10,20,30,60]
x = np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 60]]


In [9]:
a = [1,2,3,4]
b = [10,20,30,40]
y = np.array([a,b])
print(y)

[[ 1  2  3  4]
 [10 20 30 40]]


In [14]:
x = np.array([1,2,3,4], dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [15]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [19]:
x = np.random.rand(2,5)
print(x)

[[0.49941539 0.89939082 0.24278354 0.38250963 0.49944025]
 [0.41482285 0.88320554 0.65143522 0.92556433 0.27461033]]


In [20]:
np.random.randint(1,20, size = (3,3))

array([[ 1,  5,  4],
       [10, 15,  9],
       [11, 15, 19]], dtype=int32)

In [21]:
np.random.randn(2,5)

array([[-0.58442899,  0.35435323,  0.3309218 ,  0.42089426, -0.15782983],
       [-0.16895456, -1.3466285 ,  0.78948874,  0.04168723, -0.44076062]])

In [22]:
np.random.choice([2,3,4,7,8,10])

np.int64(8)

In [23]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [24]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [25]:
x = np.eye(4, k = -1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [26]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [28]:
.np.arange(0,11,2)

SyntaxError: invalid syntax (2473853886.py, line 1)

In [29]:
.np.arange(0,11,2)

SyntaxError: invalid syntax (2473853886.py, line 1)

In [30]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [31]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
a = [10,20,30,40,50]
x = np.array(a)
print(x)

[10 20 30 40 50]


In [33]:
x.ndim

1

In [34]:
b = [1,2,3,4,5]
y = np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [35]:
y.ndim

2

In [36]:
y.shape

(2, 5)

In [37]:
y.size

10

In [38]:
a = np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [39]:
np.reshape(a, (2,2))

array([[ 3,  6],
       [ 9, 12]])

In [41]:
x=np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
x.size

15

In [43]:
x.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [44]:
x=np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [45]:
y.transpose()

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4],
       [50,  5]])

In [47]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [48]:
a[2:6]

array([3, 4, 5, 6])